language: node_js

node_js:
  - "iojs"

addons:
  code_climate:
    repo_token: 5a0fa1464416d403e4069dba26a79ec632b4119f45293f3e9d948463756f3637b

before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g codecov

after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha tests/*.js --reporter lcovonly -- -R spec
  - codeclimate-test-reporter < ./coverage/lcov.info
  - codecov
